name: Auto Approve PRs

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check PR base and head
        id: check_pr
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ ("$BASE_BRANCH" == "develop") && ("$HEAD_BRANCH" == "master" || "$HEAD_BRANCH" == "release") ]]; then
            echo "APPROVE=true" >> $GITHUB_ENV
          else
            echo "APPROVE=false" >> $GITHUB_ENV
          fi

      - name: Approve PR
        if: env.APPROVE == 'true'
        uses: dkhmelenko/autoapproval@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
