name: Auto Approve PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check PR base and head
        id: check_pr
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ ("$BASE_BRANCH" == "develop") && ("$HEAD_BRANCH" == "master" || "$HEAD_BRANCH" == "release") ]]; then
            echo "APPROVE=true" >> $GITHUB_ENV
          else
            echo "APPROVE=false" >> $GITHUB_ENV
          fi

      - name: Approve PR
        if: env.APPROVE == 'true'
        uses: hmarr/auto-approve-action@v3
